### CONTAINERS ###
services:

  # MAIN ROUTER
  main-router:
    build:
      dockerfile: Dockerfile/routers/main_router/Dockerfile
    container_name: main-router
    privileged: true
    restart: unless-stopped
    networks:
      main-network:
        ipv4_address: 172.0.254.254
      internet:
        ipv4_address: 172.0.0.254

#ATTACKER
  attacker:
    build:
      dockerfile: Dockerfile/attacker/Dockerfile
    container_name: attacker
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet1:
        ipv4_address: 172.0.1.200

  # SUBNET 1
  sub1-router:
    build:
      dockerfile: Dockerfile/routers/subnet_router/subnet1/Dockerfile
    container_name: sub1-router
    privileged: true
    restart: unless-stopped
    networks:
      main-network:
        ipv4_address: 172.0.254.5
      subnet1:
        ipv4_address: 172.0.1.100

  sub1-ubu12:
    build:
      dockerfile: Dockerfile/hosts/12.04/Dockerfile
    container_name: sub1-ubu12
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet1:
        ipv4_address: 172.0.1.12

  sub1-ubu14:
    build:
      dockerfile: Dockerfile/hosts/14.04/Dockerfile
    container_name: sub1-ubu14
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet1:
        ipv4_address: 172.0.1.14
  
  sub1-ubu16:
    build:
      dockerfile: Dockerfile/hosts/16.04/Dockerfile
    container_name: sub1-ubu16
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet1:
        ipv4_address: 172.0.1.16
    
  sub1-ubu18:
    build:
      dockerfile: Dockerfile/hosts/18.04/Dockerfile
    container_name: sub1-ubu18
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet1:
        ipv4_address: 172.0.1.18
  
  sub1-ubu20:
    build:
      dockerfile: Dockerfile/hosts/20.04/Dockerfile
    container_name: sub1-ubu20
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet1:
        ipv4_address: 172.0.1.20
  
  sub1-ubu22:
    build:
      dockerfile: Dockerfile/hosts/22.04/Dockerfile
    container_name: sub1-ubu22
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet1:
        ipv4_address: 172.0.1.22

  # SUBNET 2
  sub2-router:
    build:
      dockerfile: Dockerfile/routers/subnet_router/subnet2/Dockerfile
    container_name: sub2-router
    privileged: true
    restart: unless-stopped
    networks:
      main-network:
        ipv4_address: 172.0.254.2
      subnet2:
        ipv4_address: 172.0.2.100

  sub2-ubu12:
    build:
      dockerfile: Dockerfile/hosts/12.04/Dockerfile
    container_name: sub2-ubu12
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet2:
        ipv4_address: 172.0.2.12

  sub2-ubu14:
    build:
      dockerfile: Dockerfile/hosts/14.04/Dockerfile
    container_name: sub2-ubu14
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet2:
        ipv4_address: 172.0.2.14
  
  sub2-ubu16:
    build:
      dockerfile: Dockerfile/hosts/16.04/Dockerfile
    container_name: sub2-ubu16
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet2:
        ipv4_address: 172.0.2.16
    
  sub2-ubu18:
    build:
      dockerfile: Dockerfile/hosts/18.04/Dockerfile
    container_name: sub2-ubu18
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet2:
        ipv4_address: 172.0.2.18
  
  sub2-ubu20:
    build:
      dockerfile: Dockerfile/hosts/20.04/Dockerfile
    container_name: sub2-ubu20
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet2:
        ipv4_address: 172.0.2.20
  
  sub2-ubu22:
    build:
      dockerfile: Dockerfile/hosts/22.04/Dockerfile
    container_name: sub2-ubu22
    restart: unless-stopped
    privileged: true
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet2:
        ipv4_address: 172.0.2.22

  # SUBNET 3
  sub3-router:
    build:
      dockerfile: Dockerfile/routers/subnet_router/subnet3/Dockerfile
    container_name: sub3-router
    privileged: true
    restart: unless-stopped
    networks:
      main-network:
        ipv4_address: 172.0.254.3
      subnet3:
        ipv4_address: 172.0.3.100

  sub3-ubu12:
    build:
      dockerfile: Dockerfile/hosts/12.04/Dockerfile
    container_name: sub3-ubu12
    privileged: true
    restart: unless-stopped 
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet3:
        ipv4_address: 172.0.3.12
  
  sub3-ubu14:
    build:
      dockerfile: Dockerfile/hosts/14.04/Dockerfile
    container_name: sub3-ubu14
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet3:
        ipv4_address: 172.0.3.14
    privileged: true
  
  sub3-ubu16:
    build:
      dockerfile: Dockerfile/hosts/16.04/Dockerfile
    container_name: sub3-ubu16
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet3:
        ipv4_address: 172.0.3.16
    privileged: true
    
  sub3-ubu18:
    build:
      dockerfile: Dockerfile/hosts/18.04/Dockerfile
    container_name: sub3-ubu18
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet3:
        ipv4_address: 172.0.3.18
    privileged: true
  
  sub3-ubu20:
    build:
      dockerfile: Dockerfile/hosts/20.04/Dockerfile
    container_name: sub3-ubu20
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet3:
        ipv4_address: 172.0.3.20
    privileged: true
  
  sub3-ubu22:
    build:
      dockerfile: Dockerfile/hosts/22.04/Dockerfile
    container_name: sub3-ubu22
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet3:
        ipv4_address: 172.0.3.22
    privileged: true

  # SUBNET 4
  sub4-router:
    build:
      dockerfile: Dockerfile/routers/subnet_router/subnet4/Dockerfile
    container_name: sub4-router
    privileged: true
    restart: unless-stopped
    networks:
      main-network:
        ipv4_address: 172.0.254.4
      subnet4:
        ipv4_address: 172.0.4.100

  sub4-ubu12:
    build:
      dockerfile: Dockerfile/hosts/12.04/Dockerfile
    container_name: sub4-ubu12
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet4:
        ipv4_address: 172.0.4.12
  
  sub4-ubu14:
    build:
      dockerfile: Dockerfile/hosts/14.04/Dockerfile
    container_name: sub4-ubu14
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet4:
        ipv4_address: 172.0.4.14
    privileged: true
  
  sub4-ubu16:
    build:
      dockerfile: Dockerfile/hosts/16.04/Dockerfile
    container_name: sub4-ubu16
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet4:
        ipv4_address: 172.0.4.16
    privileged: true
    
  sub4-ubu18:
    build:
      dockerfile: Dockerfile/hosts/18.04/Dockerfile
    container_name: sub4-ubu18
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet4:
        ipv4_address: 172.0.4.18
    privileged: true
  
  sub4-ubu20:
    build:
      dockerfile: Dockerfile/hosts/20.04/Dockerfile
    container_name: sub4-ubu20
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet4:
        ipv4_address: 172.0.4.20
    privileged: true
  
  sub4-ubu22:
    build:
      dockerfile: Dockerfile/hosts/22.04/Dockerfile
    container_name: sub4-ubu22
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./shared
        target: /shared
    networks:
      subnet4:
        ipv4_address: 172.0.4.22
    privileged: true



### NETWORKS ###
networks:
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
  main-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.254.0/24
  subnet1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.1.0/24
  subnet2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.2.0/24
  subnet3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.3.0/24
  subnet4:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.4.0/24
